import React from 'react';
import { DecisionType, SeverityType } from '../types';
import { StatusBadge } from './StatusBadge';
import { SeverityBadge } from './SeverityBadge';
import { formatConfidence } from '../utils/formatters';

interface DecisionCardProps {
  decision: DecisionType;
  severity: SeverityType;
  confidence: number;
  dataset: string;
}

export const DecisionCard: React.FC<DecisionCardProps> = ({
  decision,
  severity,
  confidence,
  dataset,
}) => {
  const isInsufficient = decision === 'INSUFFICIENT_EVIDENCE';
  const isIncident = decision === 'INCIDENT';
  const isSuspicious = decision === 'SUSPICIOUS';

  return (
    <div
      className={`decision-card ${decision}`}
      data-testid="decision-card"
      role="region"
      aria-label="Incident Decision"
    >
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 }}>
        <div>
          <span style={{ fontSize: 11, fontWeight: 700, letterSpacing: 0.5, textTransform: 'uppercase', color: 'var(--color-text-secondary)' }}>
            Authoritative Triage Decision
          </span>
          <h2 style={{ fontSize: 24, fontWeight: 800, marginTop: 2, display: 'flex', alignItems: 'center', gap: 10 }}>
            {decision}
            <StatusBadge status={decision} />
          </h2>
        </div>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
          <span className="badge badge-neutral">Dataset: {dataset.toUpperCase()}</span>
          <SeverityBadge severity={severity} />
        </div>
      </div>

      {isInsufficient && (
        <div
          style={{
            padding: '10px 14px',
            backgroundColor: 'rgba(154, 165, 184, 0.08)',
            borderLeft: '3px solid var(--color-insufficient-border)',
            borderRadius: 4,
            marginBottom: 12,
            fontSize: 13,
            color: 'var(--color-text-secondary)',
          }}
          data-testid="insufficient-evidence-alert"
        >
          <strong>Insufficient Evidence:</strong> The available log sequence does not support a stronger incident classification under calibrated conformal bounds.
        </div>
      )}

      {isIncident && (
        <div
          style={{
            padding: '10px 14px',
            backgroundColor: 'rgba(255, 107, 107, 0.08)',
            borderLeft: '3px solid var(--color-incident-border)',
            borderRadius: 4,
            marginBottom: 12,
            fontSize: 13,
            color: 'var(--color-incident-text)',
          }}
          data-testid="incident-confirmed-alert"
        >
          <strong>Incident Detected:</strong> Anomaly patterns verified against historical incident clusters.
        </div>
      )}

      {isSuspicious && (
        <div
          style={{
            padding: '10px 14px',
            backgroundColor: 'rgba(252, 196, 25, 0.08)',
            borderLeft: '3px solid var(--color-suspicious-border)',
            borderRadius: 4,
            marginBottom: 12,
            fontSize: 13,
            color: 'var(--color-suspicious-text)',
          }}
          data-testid="suspicious-alert"
        >
          <strong>Suspicious Activity:</strong> Anomalous characteristics observed; manual inspection recommended.
        </div>
      )}

      <div className="decision-grid">
        <div>
          <div className="decision-metric-label">Deterministic Confidence</div>
          <div className="decision-metric-value">{formatConfidence(confidence)}</div>
        </div>
        <div>
          <div className="decision-metric-label">Decision Authority</div>
          <div style={{ fontSize: 13, color: 'var(--color-text-secondary)' }}>
            Phase 8 Deterministic Engine
          </div>
        </div>
        <div>
          <div className="decision-metric-label">Engine Governance</div>
          <div style={{ fontSize: 12, color: 'var(--color-text-muted)' }}>
            Decision generated by the deterministic reasoning engine.
          </div>
        </div>
      </div>
    </div>
  );
};
