import { PipelineStageInfo } from '../components/StageInspector';

export const PIPELINE_STAGES: PipelineStageInfo[] = [
  {
    id: 'ingest',
    name: 'Ingestion & Validation',
    label: 'INGEST',
    purpose: 'Enforces strict input bounds: maximum 500 records, 4096 bytes per line, filesystem path traversal rejection, and label leakage protection.',
    input: 'Raw log sequence [500 lines max]',
    output: 'Sanitized, bounded log records',
    status: 'healthy',
    latency: '12 ms',
    implementation: 'sentinellog.serving.api.schemas.AnalyzeRequest (Pydantic v2)',
    dependencies: ['FastAPI middleware', 'Regex security guards', 'Forbidden label sanitizers'],
    failureModes: ['Payload exceeds 500 lines', 'Path traversal tokens (../, /etc/)', 'Client-side ground truth label injection'],
    isDownstreamOfGate: false,
  },
  {
    id: 'parse',
    name: 'Drain3 Log Parsing',
    label: 'PARSE',
    purpose: 'Online prefix-tree template extraction with regex masking. Converts semi-structured messages into canonical cluster IDs without supervision.',
    input: 'Bounded log text stream',
    output: 'Structured event templates (e.g. E14, E22) + variable lists',
    status: 'healthy',
    latency: '8 ms',
    implementation: 'sentinellog.ingestion.drain_parser.Drain3Parser (depth=4, sim_th=0.5)',
    dependencies: ['Drain3 TemplateMiner', 'Regex token masking'],
    failureModes: ['Unseen template drift', 'High entropy numeric parameters'],
    isDownstreamOfGate: false,
  },
  {
    id: 'score',
    name: 'Anomaly Scoring (B2)',
    label: 'SCORE',
    purpose: 'Evaluates window event sequences using lightweight learned sequential models (<2M params) to produce real-valued anomaly scores.',
    input: 'Chronological event count & template ID vectors',
    output: 'Real-valued anomaly score s in [0, inf)',
    status: 'active',
    latency: '18 ms',
    implementation: 'sentinellog.scoring.b2_sequential_gru.SequentialGRUScorer (24k params)',
    dependencies: ['PyTorch checkpoint (rule 6 <2M params)', 'Vocabulary token map'],
    failureModes: ['Window truncated below min length', 'Out-of-vocabulary template'],
    isDownstreamOfGate: false,
  },
  {
    id: 'conformal-gate',
    name: 'Conformal Selective Gate',
    label: 'CONFORMAL GATE',
    purpose: 'Finite-sample distribution-free risk control. Compares anomaly score against calibrated threshold tau(0.05)=1.1546. Auto-clears 94.8% of normal windows.',
    input: 'Anomaly score s, alpha target = 0.05',
    output: 'Binary decision: AUTO-CLEAR (94.78%) or ESCALATE (5.22%)',
    status: 'calibrated',
    latency: '2 ms',
    implementation: 'sentinellog.calibration.conformal_gate.ConformalSelectiveGate',
    dependencies: ['Phase 4 chronological calibration partition scores', 'Quantile estimator'],
    failureModes: ['Distribution shift violating exchangeability', 'Threshold uncalibrated'],
    isDownstreamOfGate: false,
  },
  {
    id: 'retrieve',
    name: 'Historical Retrieval & MMR',
    label: 'RETRIEVE',
    purpose: 'Leakage-safe semantic retrieval over chronological training/calibration partitions with Maximal Marginal Relevance (MMR, lambda=0.7) for 24.6% redundancy reduction.',
    input: 'Escalated query window representation',
    output: 'Top-k diverse historical incidents with verified root causes',
    status: 'active',
    latency: '41 ms',
    implementation: 'sentinellog.retrieval.retriever & sentinellog.reasoning.mmr.MMRReranker',
    dependencies: ['Chronological index (Phase 5/6)', 'Cosine metric space'],
    failureModes: ['Zero historical matches found', 'Candidate pool cold-start'],
    isDownstreamOfGate: true,
  },
  {
    id: 'explain',
    name: 'Grounded LLM Explainer',
    label: 'EXPLAIN',
    purpose: 'Generates structured executive summaries and claim-level hypotheses strictly constrained to citing verified historical calibration window records.',
    input: 'Escalated window + MMR-reranked citations + Phase 8 reasoning envelope',
    output: 'Structured claims (OBSERVATION, EVIDENCE, CORRELATION) with explicit citation IDs',
    status: 'active',
    latency: '392 ms',
    implementation: 'sentinellog.explanation.orchestrator.ExplanationOrchestrator',
    dependencies: ['Isolated sandboxed LLM provider (Rule 4 compliant)', 'Prompt template'],
    failureModes: ['Provider rate limit/timeout', 'Uncited hallucination attempt'],
    isDownstreamOfGate: true,
  },
  {
    id: 'verify',
    name: 'Faithfulness & Provenance',
    label: 'VERIFY',
    purpose: 'Programmatic citation grounding and cryptographic SHA-256 provenance verification. If any claim fails validation, falls back safely to deterministic reasoning.',
    input: 'Generated claims + citation registry + SHA-256 lineage store',
    output: 'VERIFIED (14/14 claims grounded) or FALLBACK status',
    status: 'verified',
    latency: '6 ms',
    implementation: 'sentinellog.explanation.verification.FaithfulnessChecker',
    dependencies: ['Phase 7 provenance engine', 'Deterministic claim parser'],
    failureModes: ['Citation ID unresolved', 'Line range mismatch', 'Contradictory claim text'],
    isDownstreamOfGate: true,
  },
];
